services:
  postgres:
    image: postgres:16
    container_name: docai-postgres

    environment:
      POSTGRES_DB: docai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

  backend:
    image: document-analyzer-backend:1.0
    container_name: document-analyzer-backend

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

    depends_on:
      - postgres