spring:
  application:
    name: DocumentAnalyzer
  datasource:
    url: jdbc:postgresql://localhost:5433/docai?options=-c%20timezone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect